### ISSUE TITLE
ducc FFT support?

### ISSUE THREAD

**Issue by mreineck** [blackwer/fft_bench#1]
Would you be interested in adding ducc FFT to the implementations? I think I could provide a PR fairly easily.

**Comment by blackwer** [comment]
Absolutely! I'm sure a PR would be straightforward, especially since I
already have a working run on your `pocketfft`. If I knew ducc existed,
it'd already be in :) Thanks!

**Comment by mreineck** [comment]
Great, I'll get working on it right away!
