### ISSUE TITLE
Suggestions for benchmark plots, and some ducc news

### ISSUE THREAD

**Issue by mreineck** [blackwer/fft_bench#5]
Especially when looking at the 1D benchmark plots it is fairly difficult to estimate the quantitative differences between all the FFT implementations, because the y axis covers so many orders of magnitude. I wonder whether it would be clearer to plot "wallclock time per grid point" instead of "wallclock time per full FFT"? The cuFinufft paper has done this, as far as I remember.

Concerning `ducc` FFT, I have been working on further reducing the multithreading overhead for small transforms, as well as improving large multithreaded 1D transforms, both with fairly good success. I'm plotting the run time changes on my laptop below (using the proposed new y-axis).

The only drawback of the change is that the new `ducc` version would require C++20, and I'm not sure how many users will be sufficiently adventurous to switch to such a recent standard...

[Edit: updated figures]

![1d_c2c_st_marvin](https://github.com/blackwer/fft_bench/assets/898507/af2dea06-d41b-4a0d-9f16-ae40acdde32b)
![2d_c2c_st_marvin](https://github.com/blackwer/fft_bench/assets/898507/ec83f898-a3a6-43c0-a4a0-7344cd10bab6)
![3d_c2c_st_marvin](https://github.com/blackwer/fft_bench/assets/898507/23b0486f-77c7-4f87-95d8-cc70831e1878)
![1d_c2c_mt_marvin](https://github.com/blackwer/fft_bench/assets/898507/f54e594b-d120-4fcc-9f70-5c4bae108c64)
![2d_c2c_mt_marvin](https://github.com/blackwer/fft_bench/assets/898507/41d95d78-126b-4e97-958f-b5ec92781731)
![3d_c2c_mt_marvin](https://github.com/blackwer/fft_bench/assets/898507/187d8001-89b9-4090-b891-6dfd3e9b8d09)

**Comment by blackwer** [comment]
Thanks for the work. I've updated the main plots to use ns/gp. I'll bump the ducc version as well and fix all the icelake stuff next week. Is this work on the main branch?

**Comment by mreineck** [comment]
> Is this work on the main branch?

No, the plots are from the `crazy_threading` branch, which is more aptly named than I thought ... there is extremely weird behavior when running this code on MacOS, and the tests come almost to a halt, but there are no deadlocks, as far as I can see. I definitely need more time before this can be released officially, but I wanted to share the news that `ducc` FFT can perhaps still be tweaked :-)

**Comment by blackwer** [comment]
Fantastic. I'll leave this open for now and maybe add a second version of `ducc` to the list since it's sufficiently different and it's nice to track this kind of thing

**Comment by mreineck** [comment]
That's a great offer, thanks!

I need to have another look, but I think I should be able to port at least the speedups for the large 1D transforms to the "traditional" version. If that works, I'll open another PR probably during the weekend.

**Comment by mreineck** [comment]
I think this can be closed.
